services:
  Shared\Bundle\:
    resource: '../../*'
    exclude: '../../{DependencyInjection,Tests}'

  Shared\Bundle\Publisher\ProductPublisher:
    autowire: true
    autoconfigure: true
    public: true